---
title: "Latest scores"
format: html
execute: 
  echo: false
---


```{r}
#| message: false
library(tidyverse)
library(rvest)
cutoff <- read_rds("last_get.rds") - seconds(30)
```

## Cutoff `r cutoff`


```{r}
html_tab <- function(url, mtime) {
  time_str <- sprintf("%02d:%02d:%02.0f", hour(mtime), minute(mtime), second(mtime))
  # time_str <- glue::glue("{hour(mtime)}:{minute(mtime)}:{round(second(mtime))}")
  my_html <- read_html(url)
  my_html %>% html_table() %>% pluck(1) %>% 
    filter(!str_detect(X1, "/")) %>% 
    filter(str_detect(X2, ":")) %>%
    rename(league = X1, ko = X2, status = X3, t1 = X4, score = X5, t2 = X6) %>% 
    mutate(time = time_str) %>% 
    select(time, league:t2)   
}
```


```{r}
enframe(list.files(path = "888", pattern = "888_.*.html", full.names = TRUE)) %>% 
  mutate(mtime = file.mtime(value)) %>% 
  filter(mtime >= cutoff) %>% 
  arrange(mtime) -> d
d %>% 
  pull(value) -> file_list
d %>% 
  pull(mtime) -> mtimes
d %>% summarize(max = max(mtime)) %>% pull(max) -> last_get
```

```{r}
nowtime <- now()
map2(file_list, mtimes, \(x, y) html_tab(x, y)) %>% 
  bind_rows() %>% 
  arrange(league, t1) %>% 
  group_by(league, t1) %>% 
  mutate(next_score = lead(score),
         last_score = lag(score),
         next_status = lead(status),
         last_status = lag(status)) %>% 
  filter( score != next_score |
            score != last_score |
            ((status == "FT") & (last_status != "FT"))) %>% 
  select(league, time, status, t1, score, t2) %>% knitr::kable()
```

Last get: `r last_get` (saved)

```{r}
write_rds(last_get, "last_get.rds")
```

