---
title: "`r format(Sys.time(), format = '%H:%M %d %b')`"
format: 
  html:
    page-layout: full
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(rvest)
library(kableExtra) # this makes html output, so all the output needs to be html
library(stringdist)
library(conflicted)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::lag)
source("888_changes_b_functions.R")
```

```{bash}
#| echo: false
rsync -a  ken@megan-laptop.local:projects/crrri/888/*.rds 888
```



```{r}
#| echo: false
#| message: false
cutoff <- read_rds("last_get.rds") + seconds(1) # previously subtract 30 seconds
# print(glue::glue("  Cutoff: {cutoff}"))
no <- read_csv("no-longer.csv")
d <- make_d_c(cutoff - hours(2))
d %>% summarize(max = max(mtime)) %>% pull(max) -> last_get
d %>% pull(value) -> file_list
my_url <- "~/r-projects/world-football/predictions.rds"
nowtime <- now()
predictions <- read_rds(my_url)
predictions2 <- make_current_predictions(predictions, nowtime)
latest_scores <- make_latest_scores_d(d)
if (nrow(predictions2) == 0) {
  d1a <- make_d1a(latest_scores)
} else {
  d1 <- make_d1(latest_scores, predictions2)
}
```

```{r}
#| echo: false
# cat("\n")
# print(glue::glue("Last get: {last_get} (saved)"))
write_rds(last_get, "last_get.rds")
```

## Status

```{r}
#| echo: false
tribble(
  ~status, ~time,
  "cutoff", cutoff,
  "last get", last_get
) %>% kbl() %>% 
  kable_minimal(full_width = FALSE)
```


## Matched games

```{r}
#| error: true
#| echo: false
display_matched_games_d(d1, no)
```

## Matched leagues (but not games)

```{r}
#| error: true
#| echo: false
display_non_matched_games(d1)
```

## Non-matched leagues

```{r}
#| error: true
#| echo: false
display_non_matched_leagues(d1)
```

## Results when no predictions

```{r}
#| error: true
#| echo: false
display_d1a(d1a) # this will throw an error in the likely case that there is none
```

## Ongoing games

```{r}
#| echo: false
latest_time <- file_list[(length(file_list))]
latest_time %>% read_rds() %>% 
  left_join(no, join_by(league)) %>% 
  filter(!is.na(info) & info != "no") %>% 
  filter(status != "FT") %>% 
  select(info, ko:t2) %>% 
  arrange(ko) %>% 
  kbl() 
# %>% 
#   kable_minimal(full_width = FALSE)
  
```


